M48
; DRILL file {KiCad 8.0.4} date 2025-05-03T00:51:24+0530
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-05-03T00:51:24+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0669
%
G90
G05
T1
X3.0764Y-3.1552
X3.352Y-3.1552
X5.1457Y-3.1537
X5.4213Y-3.1537
M30
